name: Test deployment

# When a new pull request is made to 'master', there's an action that ensures the site builds successfully, without actually deploying. This job will be called test-deploy

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        working-directory: ./website
        run: npm install --frozen-lockfile
      - name: Test build website
        working-directory: ./website
        run: npm run build